CREATE TABLE IF NOT EXISTS sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    broadcasted_count INTEGER NOT NULL DEFAULT 0,
    total_count INTEGER NOT NULL,
    is_processing BOOLEAN DEFAULT FALSE,
    has_error BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT sequences_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sequences_txs (
    sequence_id BIGINT NOT NULL REFERENCES sequences (id) ON DELETE CASCADE,
    position_in_sequence INTEGER,
    tx VARCHAR NOT NULL
);
 
CREATE INDEX IF NOT EXISTS sequences_id_is_processing_idx ON sequences (id, is_processing);

CREATE INDEX IF NOT EXISTS sequences_txs_id_idx ON sequences_txs (sequence_id);
